filebeat.inputs:
  - type: filestream
    id: node-app
    enabled: true
    paths:
      - /var/log/messages
    fields:
      service: devops-e2e-node
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]
